[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
bytecode_hash = "ipfs"
via_ir = true
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "layerzero/=lib/solidity-examples/contracts/",
  "solmate/=lib/solmate/src/"
]

[fmt]
line_length = 100
tab_width = 2
